{
 "title": "DoS Detector Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Gauge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time(\n  {job=\"python-forwarder\", env=\"lab\"} \n  | regexp `cpu=(?P<cpu>[0-9]+\\.[0-9]+)`\n  | unwrap cpu [5m]\n)"
    }
   ]
  },
  {
   "title": "Alert Counter",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"python-forwarder\", env=\"lab\"} |= \"ALERT\" [3h])"
    }
   ]
  },
  {
   "title": "BPS Gauge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({job=\"python-forwarder\", env=\"lab\"} \n  | regexp \"net_bps=(?P<net_bps>[0-9]+)\" \n  | unwrap net_bps [1m])"
    }
   ]
  },
  {
   "title": "IP Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(20,\n  sum by (src_ip) (\n    sum_over_time(\n      {job=\"python-forwarder\", env=\"lab\"} \n      | regexp \"src=(?P<src_ip>[0-9\\\\.]+).*connections=(?P<connections>\\\\d+)\"\n      | src_ip != \"127.0.0.1\"\n      | unwrap connections [5m]\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Network Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({job=\"python-forwarder\", env=\"lab\"} \n  | regexp \"net_bps=(?P<net_bps>[0-9]+)\" \n  | unwrap net_bps [1m])"
    }
   ]
  },
  {
   "title": "Alert Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"python-forwarder\", env=\"lab\"} |~ \"ALERT\""
    }
   ]
  },
  {
   "title": "General Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"python-forwarder\", env=\"lab\"}"
    }
   ]
  }
 ]
}